import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import {
  bumpPackageVersion,
  createManualBumpBranchName,
  normalizeReleaseTag,
  readCargoLockWorkspacePackageVersions,
  readCargoWorkspacePackageVersion,
  updatePackageManifest,
} from "../scripts/bump-release-version.mjs";

async function writeReleaseWorkspaceFixture(
  tempRoot,
  { packageVersion = "0.2.0-alpha.1", cargoVersion = packageVersion } = {},
) {
  const manifestPath = path.join(tempRoot, "package.json");
  const cargoTomlPath = path.join(tempRoot, "Cargo.toml");
  const cargoLockPath = path.join(tempRoot, "Cargo.lock");

  await fs.writeFile(
    manifestPath,
    `${JSON.stringify(
      {
        name: "@jeremyfellaz/kratos",
        version: packageVersion,
        optionalDependencies: {
          "@jeremyfellaz/kratos-darwin-arm64": packageVersion,
          "@jeremyfellaz/kratos-win32-x64-msvc": packageVersion,
        },
      },
      null,
      2,
    )}\n`,
  );

  await fs.writeFile(
    cargoTomlPath,
    `[workspace]
members = [
  "crates/kratos-core",
  "crates/kratos-cli",
]
resolver = "2"

[workspace.package]
version = "${cargoVersion}"
edition = "2021"
license = "MIT"
`,
  );

  await fs.writeFile(
    cargoLockPath,
    `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "kratos-cli"
version = "${cargoVersion}"
dependencies = [
 "kratos-core",
]

[[package]]
name = "kratos-core"
version = "${cargoVersion}"

[[package]]
name = "semver"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"
`,
  );

  return {
    manifestPath,
    cargoTomlPath,
    cargoLockPath,
  };
}

test("normalizeReleaseTag accepts bare versions", () => {
  assert.equal(normalizeReleaseTag("1.2.3"), "v1.2.3");
  assert.equal(normalizeReleaseTag("v1.2.3-beta.1"), "v1.2.3-beta.1");
});

test("updatePackageManifest syncs root and optional dependency versions", () => {
  const pkg = {
    name: "@jeremyfellaz/kratos",
    version: "0.2.0-alpha.1",
    optionalDependencies: {
      "@jeremyfellaz/kratos-darwin-arm64": "0.2.0-alpha.1",
      "@jeremyfellaz/kratos-linux-x64-gnu": "0.2.0-alpha.1",
    },
  };

  const updated = updatePackageManifest(pkg, "0.2.0");

  assert.equal(updated.version, "0.2.0");
  assert.deepEqual(updated.optionalDependencies, {
    "@jeremyfellaz/kratos-darwin-arm64": "0.2.0",
    "@jeremyfellaz/kratos-linux-x64-gnu": "0.2.0",
  });
});

test("createManualBumpBranchName avoids collisions for distinct valid prerelease tags", () => {
  const dotted = createManualBumpBranchName("v1.2.3-alpha.1");
  const hyphenated = createManualBumpBranchName("v1.2.3-alpha-1");

  assert.notEqual(dotted, hyphenated);
  assert.match(dotted, /^codex\/manual-bump-master-v1-2-3-alpha-1-[0-9a-f]{8}$/);
  assert.match(hyphenated, /^codex\/manual-bump-master-v1-2-3-alpha-1-[0-9a-f]{8}$/);
});

test("createManualBumpBranchName distinguishes base refs for the same tag", () => {
  const master = createManualBumpBranchName("v1.2.3", "master");
  const release = createManualBumpBranchName("v1.2.3", "release/1.x");

  assert.notEqual(master, release);
  assert.match(master, /^codex\/manual-bump-master-v1-2-3-[0-9a-f]{8}$/);
  assert.match(release, /^codex\/manual-bump-release-1-x-v1-2-3-[0-9a-f]{8}$/);
});

test("bumpPackageVersion rewrites package.json, Cargo.toml, and Cargo.lock from tag input", async () => {
  const tempRoot = await fs.mkdtemp(path.join(os.tmpdir(), "kratos-bump-version-"));
  const { manifestPath, cargoTomlPath, cargoLockPath } = await writeReleaseWorkspaceFixture(tempRoot);

  const result = await bumpPackageVersion("v0.2.0", manifestPath);
  const updated = JSON.parse(await fs.readFile(manifestPath, "utf8"));
  const cargoToml = await fs.readFile(cargoTomlPath, "utf8");
  const cargoLock = await fs.readFile(cargoLockPath, "utf8");

  assert.equal(result.version, "0.2.0");
  assert.equal(result.tag, "v0.2.0");
  assert.equal(result.cargoTomlPath, cargoTomlPath);
  assert.equal(result.cargoLockPath, cargoLockPath);
  assert.deepEqual(result.cargoLockPackageNames, ["kratos-cli", "kratos-core"]);
  assert.equal(updated.version, "0.2.0");
  assert.deepEqual(updated.optionalDependencies, {
    "@jeremyfellaz/kratos-darwin-arm64": "0.2.0",
    "@jeremyfellaz/kratos-win32-x64-msvc": "0.2.0",
  });
  assert.equal(readCargoWorkspacePackageVersion(cargoToml), "0.2.0");
  assert.deepEqual(readCargoLockWorkspacePackageVersions(cargoLock), [
    {
      name: "kratos-cli",
      version: "0.2.0",
    },
    {
      name: "kratos-core",
      version: "0.2.0",
    },
  ]);
  assert.match(cargoLock, /name = "semver"\nversion = "1\.0\.0"\nsource = /);
});

test("bumpPackageVersion rejects downgrades and same-version rewrites", async () => {
  const tempRoot = await fs.mkdtemp(path.join(os.tmpdir(), "kratos-bump-version-"));
  const { manifestPath } = await writeReleaseWorkspaceFixture(tempRoot);

  await assert.rejects(
    bumpPackageVersion("v0.1.0", manifestPath),
    /Target version 0\.1\.0 must be greater than current version 0\.2\.0-alpha\.1/,
  );

  await assert.rejects(
    bumpPackageVersion("v0.2.0-alpha.1", manifestPath),
    /Target version 0\.2\.0-alpha\.1 must be greater than current version 0\.2\.0-alpha\.1/,
  );
});
